### PR TITLE
SchemaInstance

### PR DESCRIPTION
**Pull request by deadman2000**
improved performance and memory usage by schema instances
added|modified JSDoc
added new schema tests
added SchemaBuilderEntity.instancePrototype

### CODE REVIEW

**Comment by petersirka** [comment]
I'll try it.

**Comment by petersirka** [comment]
Thanks.

**Comment by petersirka** [comment]
I have seen it and it's really nice.
1000x thanks.

**Comment by petersirka** [comment]
I found a problem with MongoDB. The `SchemaInstance.$clean()` is for MongoDB needed because the MongoDB module uses for calculating document's size this:

```javascript
for (var key in obj) {
    // all properties with $_schema (I renamed it to $schema).
}
```

image

I was looking for the problem 30 minutes and some my projects didn't work.
So the `$clean()` creates a copy of the model and removes all hidden unnecessary properties.
Currently is everything OK in `v1.9.6` branch on the GitHub.

Thanks.

**Comment by deadman2000** [comment]
@petersirka 
Renaming was not necessary. Problem was in schema reference.
I tested on my project new version works fine.
I named reference `$_schema` because `SchemaInstance` has already function `$schema` in prototype. Now calling `instance.$schema()` throws exception: `TypeError: [...].$schema is not a function`

**Comment by deadman2000** [comment]
I recommend remove `$schema` back to `$_schema` and change in `SchemaBuilderEntity.prototype.clean` to this:
```javascript
	if (model.$_schema)
		delete model.$_schema;
```

**Comment by petersirka** [comment]
Yes, you're right. Shit happen.
I have renamed it to `$$schema` because exist `$$async` and `$$result`. Thanks.

PS: this doesn't work:

```javascript
if (model.$_schema)
        delete model.$_schema;
// we must crawl all properties and all array values
```

This solution works correctly:
<https://github.com/totaljs/framework/blob/v1.9.6/builders.js#L1897>

Thanks again.

**Comment by deadman2000** [comment]
@petersirka 
I'm sorry for that. I specially pulled this version in beta branch for testing before release.

**Comment by petersirka** [comment]
No no no, please don't apologize. I copie each change from the latest branch into my server because I can see all bugs. I'm testing all changes and some things we can't test. `AppMonitor` says truth :+1: about all bugs.

Your change is a benefit for the framework.
Thanks again!

**Comment by deadman2000** [comment]
I found bug with array properties. `$clean` change original array. Way to fix:
```javascript
		if (value instanceof Array) {
			var newarr = [];
			for (var j = 0, sublength = value.length; j < sublength; j++) {
				var item = value[j];
				if (item instanceof SchemaInstance)
					newarr.push(self.clean(item, false));
				else
					newarr.push(item);
			}
			model[key] = newarr;
			continue;
		}
```

@petersirka please, try to use in mongo SchemaInstance without `clean`.

**Comment by petersirka** [comment]
The framework doesn't change original array because:
https://github.com/totaljs/framework/blob/v1.9.4/builders.js#L2108 the framework copies all values to new plain object `framework_utils.copy(m)`.

Or do you test it? I didn't test array.

**Comment by petersirka** [comment]
Yes, you're right.
I'll fix it.

**Comment by deadman2000** [comment]
@petersirka wath about mobgo? Can you try it?

**Comment by petersirka** [comment]
I think that best solution for it will be:

- serialize to JSON with the filter for unnecessary properties
- deserialize
- return object

MongoDB? I must test it.

**Comment by petersirka** [comment]
I have added new `clone` function.
I think that's everything ok now.

Please download latest branch or download new beta from NPM `npm install total.js@beta`. There is your update with `U.request()`.

**Pull request merged**
