### PR TITLE
Improve time complexity for F.schedules management

### PR DESCRIPTION
**Pull request by fgnm**
I've tried to improve time complexity of F.schedules as for #751, please let me know what do you think, there are still some improvements that can be done, for example a better management of `owner` property. But I'm still quite unfamiliar with internal framework's code. So, at moment, this is the best I can do.

### CODE REVIEW

**Comment by petersirka** [comment]
And what will be a benefit? Because you can obtain scheduler instance easily too via:

```js
var scheduler = F.schedules.findItem('id', YOUR_SCHEDULER_ID);
```
Everything is a bit same but the current call of schedulers for execution is a bit effective than your.

**Comment by fgnm** [comment]
Time complexity to find and remove a schedule. With `findItem` you have an `O(n)` reaserch time in the array, using an JavaScript `Object` you have the advantages of internal JS hashes, so find and remove schedules it's much more efficient because it can be done in `O(1)`.

Even the function `slice` (used [here](https://github.com/totaljs/framework/blob/5efb42c7f0f9371474cc133dcb0a572ac4fe540a/index.js#L8083)), has a time complexity of `O(n)`, so I think that this solution might improve a lot performances, especially if I have to handle more then 10k schedules that has to be added and removed constantely.

**Comment by petersirka** [comment]
> Time complexity to find and remove a schedule.

Yes - **I agree**,  but I don't expect that schedulers will be removed too often. I'll look into it + maybe I'll measure it.

**Comment by fgnm** [comment]
Correct me if I wrong but current call of schedulers for execution is `O(n^2)` becuase `slice` operation. With this chnages it's reduced to `O(n)`.

>  but I don't expect that schedulers will be removed too often.

It depends on use-case, I'm building a turn based game, so in 1 minute it can be scheduled 5/10 actions just for a single pair of users, that has to be executed in few seconds and then removed. It really depends on players actions but having an `O(n^2)` is not a great idea anyway.

**Comment by petersirka** [comment]
Try it: `$ npm install total.js@beta`. I'm going to test it on my server.

**Comment by fgnm** [comment]
Thanks! I'll stress it too in the next days.

**Pull request merged**
