### PR TITLE
customize directories, fix debug.js

### PR DESCRIPTION
**Pull request by luoage**
customize directories, fix debug.js

### CODE REVIEW

**Comment by luoage** [comment]
@peterkc 

I have already performed the update to v2.8.1. The older merge request has already closed. Did it right ?

**Comment by petersirka** [comment]
Thank you! I have improved it a bit.
Can you send me your real name? I have added you to contributor's list.

+1

**Comment by luoage** [comment]
My real name ? OK, my real name is 金岭, from China. The nickname of luoage is also good.

**Comment by luoage** [comment]
By the way, when will the new version be released? 😆

**Comment by petersirka** [comment]
:-D I can add your real name ... or is there a way to translate it to English? I can replace your name in readme for the real name (I don't have any problem with it) :-D.

I have published a new beta version: `$ npm install total.js@beta`. And new release: I don't know, maybe next month.

**Comment by luoage** [comment]
I don't know how to translate it. 

Thanks for your attention.

**Pull request merged**
