### PR TITLE
Adding Multi-Mapping prototype to the framework

### PR DESCRIPTION
**Pull request by binarygeotech**
This allows multi-mapping of routes

**urls as object**
```
F.mmap({
        urls: ['/url-001', '/url-002', '/url-003'],
        suffix: ['imgs', 'js', 'css']
    },
    ['imgs', 'js', 'css']);
```

or 
**urls as array**
```
F.mmap(['/url-001', '/url-002', '/url-003'],
    ['imgs', 'js', 'css']);
```

### CODE REVIEW

**Comment by molda** [comment]
I've notice in your code 2 mistakes->  `link[-1]` and `url[-1]` will always be undefined, so this 
`if(link[-1]` === '/')` wil always be `false`.

Also can you show what mapping is this suppose to produce?

I tried your code and where you call `self.map(link, files[i]);` the link is `/url-001imgs` and `files[i]` is `imgs` which doesn't make any sense.

**Comment by petersirka** [comment]
Sorry, but I don't see any benefits of this method. It's useless for most of projects. I recommend to create a module with same functionality.

Thank you!

**Comment by binarygeotech** [comment]
@molda, that ``` link[-1] ``` is a typo when adding it to the framework as a prototype.

@petersirka, I have it as a module in my project, and I thought it will be nice if it can be added to the framework.

I thought there are some things that is good to be part of a framework, that is why I created a pull request. The method works well in handling routes with relative path and query string is not an option.
It might seems not useful to you, but someone out there might need such functionality.

I will add it as part of my crafted modules though.
Thank you guys for pointing out some useful facts.

**Comment by petersirka** [comment]
@binarygeotech I appreciate it. I want `fit` framework and advanced mapping (according to me) is useless. A module is good way for it.

Thank you!

**Pull request closed without merging**
