### PR TITLE
Pagination fixed for first page.

### PR DESCRIPTION
**Pull request by DusanDragulaGR**
In some cases will be pageFrom = 0, but I think it can't be 0.

### CODE REVIEW

**Comment by petersirka** [comment]
Thanks!

**Comment by petersirka** [comment]
I'm thinking about it and that's not good idea, because pagination starts from 1. Otherwise: `pagination.first()` starts from `1` not from `0`. I have to perform a rollback :+1: but thanks!

**Comment by petersirka** [comment]
Bohes dobre si to dal!
Ja som sa zase pomýlil. Ja som k*... ospravedlňujem sa. Vraciam späť :-D

**Comment by DusanDragulaGR** [comment]
Prave som to formuloval, som sa zle vyjadril :)
Davalo to 0 pri situacii pageTo == pages == max.

**Comment by petersirka** [comment]
Fakt sa ospravedlňujem, je to tam.
10000000x :100:  sorry a ďakujem

**Comment by petersirka** [comment]
@DusanDragulaGR publikoval som novú beta `npm install total.js@beta` -- ešte raz dík.

**Comment by DusanDragulaGR** [comment]
Super, ja ďakujem.

**Pull request merged**
