### PR TITLE
update shebang

### PR DESCRIPTION
**Pull request by ckpiggy**
update shebang since the script should run with bash according to totaljs/framework/issues/525

### CODE REVIEW

**Comment by petersirka** [comment]
`run.sh` is prepared for Travis, I need to test it on Travis. It's a bit complicated.

**Comment by ckpiggy** [comment]
I just noticed the build history got a lot error logs in Travis. 
Do you have any clue or suggestion? 
I am very glad to send a PR about that.

**Comment by ckpiggy** [comment]
I saw this error on Travis, and it is because this line in test/test-javascript.js
```
assert.ok(Buffer.from(javascript.compile_javascript(fs.readFileSync('javascript.js').toString('utf8'))).toString('base64') === 'cmV0dXJuJ1xcJysyO3ZhciBhdHRyaWJ1dGVzPSJcXFsiK2ErIiooIitiKyIpKD86IitjKyIqKFsqXiR8IX5dPz0pIitkKyIqKD86JygoPzpcXFxcLnxbXlxcXFwnXSkqKSd8XCIoKD86XFxcXC58W15cXFxcXCJdKSopXCJ8KCIrZSsiKSl8KSIrZisiKlxcXSI7dmFyIGE9MjAwOw==', 'Problem 1');
```
That is because `Buffer.from` [was introduced in node version 6.0](https://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha)

Travis use node version 4.0
```
{
  "language": "node_js",
  "cache": [
    "npm"
  ],
  "node_js": "4.0",
  "install": [
    "npm install"
  ],
  "script": [
    "cd test",
    "sh run.sh"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
```
How about use node 6.11.1 LTS in Travis ?

**Comment by petersirka** [comment]
Thank you. We can use node 6.11 in travis, can you update it?

**Comment by ckpiggy** [comment]
no problem

**Pull request merged**
